// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'form-group': string;
  'heading-container': string;
  'popup-container': string;
}
export const cssExports: CssExports;
export default cssExports;
