// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formgroup': string;
  'heading': string;
  'popup-container': string;
}
export const cssExports: CssExports;
export default cssExports;
